# Generated by Django 4.2.8 on 2023-12-10 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='middle_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='surname',
        ),
    ]
